version: '3.8'

services:
  clubwiz-frontend:
    image: clubwiz-frontend
    container_name: clubwiz-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    mem_limit: 512m
    ports:
      - "3000:3000"
    networks:
      - clubwiz-network

networks:
  clubwiz-network:
    external: true