default_platform(:android)

platform :android do
  desc "Deploy to Google Play production as a draft"
  lane :deploy do
    upload_to_play_store(
      track: "production",
      release_status: "draft",
      aab: "android/app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      changes_not_sent_for_review: true
    )
  end
end
